spring:
  application:
    name: v2ray-ui

server:
  port: 8089


json:
  file:
    originPath: /etc/v2ray/config.json
    resultPath: /etc/v2ray/config.pwd
    json

nginx:
  filePath: /etc/nginx/conf.d
  templateFile: /root/v2ray/sources/LocTemplateDirectory/nginxTemplate.loc


shell:
  filePath: /root/v2ray/sources/ShellDirectory/v2rayNginx.sh
  jsonPath: /root/v2ray/sources/ShellDirectory/backupJson.sh